/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

/**
 * 
 * runnable_avg_yN_inv[]表包括32个下标，对应过去0～32ms的负载贡献的衰减因子
 * 
 * 这个是怎么计算的？ 先参考: [001.UNIX-DOCS/016.负载计算.md] 
 *     & [Run Linux Kernel (2nd Edition) Volume 1: Infrastructure.epub]#8.2.7　PELT代码分析
 * 
 */
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff, /*y^0 * 2^32*/
	0xfa83b2da, /*y^1 * 2^32*/
	0xf5257d14, /*y^2 * 2^32*/
	0xefe4b99a, 0xeac0c6e6, 0xe5b906e6, 0xe0ccdeeb, 0xdbfbb796, 0xd744fcc9,
	0xd2a81d91, 0xce248c14, 0xc9b9bd85, 0xc5672a10, 0xc12c4cc9, 0xbd08a39e,
	0xb8fbaf46, 0xb504f333, 0xb123f581, 0xad583ee9, 0xa9a15ab4, 0xa5fed6a9,
	0xa2704302, 0x9ef5325f, 0x9b8d39b9, 0x9837f050, 0x94f4efa8, 0x91c3d373,
	0x8ea4398a, 0x8b95c1e3, 0x88980e80, 0x85aac367, 0x82cd8698,
};

#define LOAD_AVG_PERIOD 32   // 半衰期 ms
#define LOAD_AVG_MAX 47742   // 表示在无限个时间周期里，历史累计衰减总时间的最大值是多少


/**
 * LOAD_AVG_MAX 涉及量化负载的计算，
 * 查阅: [Run Linux Kernel (2nd Edition) Volume 1: Infrastructure.epub]#8.2.7　PELT代码分析#4．LOAD_AVG_MAX宏
 * 
 * 
 */